language: c

services:
  - docker

before_install:
- docker pull oos1111/mit-6.828
- docker run --rm -v ${PWD}:/home/mit-6.828-learning oos1111/mit-6.828 /bin/sh -c "cd /home/mit-6.828-learning; make"
- docker ps

script: .travis/script.sh

